# Generated by Django 5.0.2 on 2024-04-02 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='uploads',
            name='submission_page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.postbox'),
        ),
    ]
